---
deployment:
  tasks:
    - export DEPLOYPATH=/home/samgunof/nodejs/placefinder_api/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp .sequelizerc $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
