name: Deploy to cPanel
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Pull Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Sync Code
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
